### PR TITLE
build successes

### PR DESCRIPTION
**Pull request by almanac1914**

### CODE REVIEW

**Review by Rommelua — CHANGES_REQUESTED** [review]
image

Java Cl checks failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the mvn clean package command in the terminal and make sure that all checks pass. After that, the mentor will be able to review the homework

**Comment by almanac1914** [comment]
tests
Thank you for telling me. I have done that before making a Pull Request. All checks were successful completed. 
What is wrong with my files?

**Review by sokimaaa — CHANGES_REQUESTED** [review]
image

Java Cl checks failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the mvn clean package command in the terminal and make sure that all checks pass. After that, the mentor will be able to review the homework

**Comment by almanac1914** [comment]
> image
> 
> Java Cl checks failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the mvn clean package command in the terminal and make sure that all checks pass. After that, the mentor will be able to review the homework

Dear [sokimaaa](https://github.com/sokimaaa) have you check my reply to [Rommelua](https://github.com/Rommelua)?

**Review by Rommelua — CHANGES_REQUESTED** [review]
You have 11 files changed...
You should have only 1 file changed - class FileWork
image

**Pull request closed without merging**
